services:
  - type: web
    name: my-express-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node -r dotenv/config --experimental-json-modules src/index.js"
    envVars:
      - key: NODE_ENV
        value: production
